var constance = require('constance');

module.exports = constance('FILE_MANAGER_CONSTANTS_', [
  'CHANGE_PATH',
  'WATCH_DIRECTORY',

  'SORT_FILES_BY',
  'UPDATE_FILES_THUMBS',

  'SET_FILE_SELECTION',
  'MOVE_SELECTION',

  'CREATE_DIRECTORY',
  'OPEN_FILE',
  'REMOVE_FILE',
  'OPEN_FILE_PROPERTIES',
  
  'ICON_TYPE_OXYGEN'
]);